/**
 * スキル・爆発の効果を「紐づけない」と決めたものと、その理由（手で決める一覧）
 *
 * 対応表（src/data/effect_key_coverage.json）で、紐づけの無いキー・アクション定義のうち、ここに載っているものは
 * 理由つきの「決定済み」として扱う。載っていないもの（かつ自動で理由が付かないもの）は「未検討」になる。
 * 決めた日と決めた人（ユーザー / 実測）をメモに残す。
 */
import type { UnlinkedReason } from './effectKeyCoverage.ts';

export interface Decision {
  reason: UnlinkedReason;
  note: string;
}

/** gcsim のキー → 理由 */
export const KEY_DECISIONS: Record<string, Decision> = {
  // ユーザー決定（2026-09-30）
  'lyney-q-mark': { reason: 'covered-by-main', note: 'リネの爆発: ファニーハット・キャット変身 3 秒は本体（lyney-q）のバーで表示' },
  'itto-q-atkspd': { reason: 'covered-by-main', note: '荒瀧一斗の爆発: 爆発モードの持続は本体（itto-q）のバーで表示' },
  'ayato-burst-mark': { reason: 'covered-by-main', note: '神里綾人の爆発: 18 秒の持続は本体（ayato-burst）のバーで表示' },
  'lumidouce-scent-reset': { reason: 'grace-window', note: 'エミリエ: 芳香を集められない状態が 8 秒続くとランク 1 に戻る猶予時間。効果本体は lumidouce-case' },
  'odette-skill-recast': { reason: 'grace-window', note: 'オデット: スキルを再発動できる猶予時間（約 6 秒）。効果本体は odette-dance-double' },
  'yae_oldest_totem_expiry': { reason: 'deferred', note: "八重神子: 最初に置いた殺生櫻の残り存在時間。6-6「ストックできるスキルへの対応」で扱う（ユーザー決定 2026-09-30）" },
  'ifa-plunge-available': { reason: 'grace-window', note: 'イファ: 落下攻撃ができる短い窓（約 0.4 秒）。夜魂の状態（nightsoul-blessing）を効果時間にしている' },
  'chasca-plunge-available': { reason: 'grace-window', note: 'チャスカ: 同上' },
  'wanderer-plunge-available': { reason: 'grace-window', note: '放浪者: 落下攻撃ができる短い窓（約 0.4 秒）。効果本体は windfavored-state' },
  // ユーザー決定（2026-09-30）: 常時で登録された内部の蓄積・数え。ゲーム画面の効果ではなく、判断に使う情報ではない
  'aloy-coil-stacks': { reason: 'decided-not-linked', note: 'アーロイ: コイルの蓄積数（内部の数え）' },
  'qiqi-revelation-ssc': { reason: 'decided-not-linked', note: '七七: 啓示（内部の状態）' },
  'qiqi-revelation-ssw': { reason: 'decided-not-linked', note: '七七: 啓示（内部の状態）' },
  'sigewinne-bubble-tier': { reason: 'decided-not-linked', note: 'シグウィン: 泡の段階（蓄積状態）' },
  'traveler-story-quest-buffs': { reason: 'decided-not-linked', note: '旅人: ストーリークエスト報酬の基礎ステータス' },
  // ---- 未検討 118 件の整理（2026-09-30 ユーザー決定: D・G・H・J 以外は推奨の扱い）----
  "albedo-c2": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "amber-c6": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "ayato-c4": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "beidouc6": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "chongyun-c2": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "diluc-c6-dmg": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "diluc-c6-speed": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "eula-c1": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "ganyu-c6": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "klee-c6": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "kokomi-c4": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "layla-c4": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "lisa-c2": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "mona-c2-hexerei-post-burst-ca": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "thoma-c6": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "xingqiu-c2": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "yelan_c6": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "yelan-c4": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "yelanc4": { reason: "deferred", note: "命ノ星座の効果。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  "collei-a1": { reason: "covered-by-passive", note: "固有天賦の効果。発動バフ（固有天賦）として扱う（6-3c。ユーザー決定 2026-09-30）" },
  "shenhe-a1": { reason: "covered-by-passive", note: "固有天賦の効果。発動バフ（固有天賦）として扱う（6-3c。ユーザー決定 2026-09-30）" },
  "thoma-a1": { reason: "covered-by-passive", note: "固有天賦の効果。発動バフ（固有天賦）として扱う（6-3c。ユーザー決定 2026-09-30）" },
  "yaoyao-a4": { reason: "covered-by-passive", note: "固有天賦の効果。発動バフ（固有天賦）として扱う（6-3c。ユーザー決定 2026-09-30）" },
  "dehya-jump-kick-window": { reason: "grace-window", note: "再発動・発動条件の猶予の短い窓（効果ではない）" },
  "prune-skill-recast-window": { reason: "grace-window", note: "再発動・発動条件の猶予の短い窓（効果ではない）" },
  "xianyun-a4-window": { reason: "grace-window", note: "再発動・発動条件の猶予の短い窓（効果ではない）" },
  "furina-fanfare-debounce": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "leap-back": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "mavuika-cdc-lockout": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "skirk-burst-extinction": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "skirk-burst-extinction-anim": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "skirk-hold-e-anim": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "collei-a4-modcheck": { reason: "decided-not-linked", note: "内部（デバウンス・ロックアウト・アニメーション・確認用・短い状態）で、効果のバーにしない" },
  "shield:Tidecaller (Shield)": { reason: "decided-not-linked", note: "反撃用の短いシールドでバーにしない（対象側の決定に合わせる）" },
  "shield:Opening Flourish (Shield)": { reason: "decided-not-linked", note: "反撃用の短いシールドでバーにしない（対象側の決定に合わせる）" },
  "shield:Sacred Rite: Heron's Sanctum (Shield)": { reason: "decided-not-linked", note: "反撃用の短いシールドでバーにしない（対象側の決定に合わせる）" },
  "construct:LunarCrystallize": { reason: "decided-not-linked", note: "反応で生じる設置物で、アクションの効果ではない" },
  "zhongli-anemo": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-cryo": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-dendro": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-electro": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-geo": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-hydro": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-physical": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  "zhongli-pyro": { reason: "decided-not-linked", note: "鍾離のシールドに付随する元素別の内部状態（各1秒）でバーにしない" },
  // ---- 同じ効果・同じ持続期間のものが別で紐づけ済み（2026-09-30 ユーザー決定）----
  "bennett-field": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "chongyun-field": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "ganyu-field": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "lauma-burst": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "damage:Xingqiu Orbital": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "damage:Lea Lotus Lamp": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "damage:Bake-Kurage": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "damage:Kamisato Art: Suiyuu": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "damage:Bogglecat Box": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  "damage:Stone Stele (Tick)": { reason: "covered-by-main", note: "同じ効果・同じ持続期間のものが、本体のバー（別のキー）で紐づけ済み" },
  // フリーナ: ソース（furina/cons.go）で命ノ星座6の効果（c6Key）と確認。スキル本体の効果ではない（ユーザー決定: 命ノ星座のグループ）
  "center-of-attention": { reason: "deferred", note: "フリーナ: 命ノ星座6の効果（10秒）。6-A2（命ノ星座の扱い）の実装時に扱いを決める（ユーザー決定 2026-09-30）" },
  // ---- G（耐性ダウン・被ダメ増）は推奨どおりに決定、J・D は一旦保留（2026-09-30 ユーザー決定）----
  "omen-debuff": { reason: "covered-by-main", note: "モナの爆発: 星命定軌は mona-omen（含まれる）と mona-bubble（本体）で紐づけ済み" },
  "damage:Sesshou Sakura Tick": { reason: "deferred", note: "八重神子のスキルの継続ダメージ。6-6「ストックできるスキルへの対応」で扱う（ユーザー決定 2026-09-30）" },
  // ---- H（印）は「命中で更新される内部状態」に決定（2026-09-30 ユーザー決定）----
  // ---- J の個別確認（2026-09-30 ユーザー決定: 反応・命中・被ダメージ由来と、別のキーで表示済みのものは紐づけない）----
  "apex-drive": { reason: "decided-not-linked", note: "ヴァレサ: 落下攻撃のあとに付く 2.3 秒の状態（攻撃の分類。スキル・爆発の効果ではない）" },
  "lauma-spirit-envoy": { reason: "decided-not-linked", note: "ラウマ: 重撃（長押し）で入る鹿の状態（攻撃の分類）" },
  "gorou-e-defbuff": { reason: "covered-by-main", note: "ゴロー: スキルの旗の領域内で更新される防御バフ。本体 gorou-e-warbanner で表示済み" },
  "aloy-rushing-ice": { reason: "covered-by-main", note: "アーロイ: 本体 rushingice と同じ関数で登録する、同じ 10 秒の攻撃付与" },
  "dehya-burst-kick": { reason: "grace-window", note: "ディシア: 爆発中のキックまでの 0.77 秒の窓" },
  "gaming-man-chai": { reason: "grace-window", note: "嘉明: 爆発中の万歳の獅子が歩いて戻る間の内部状態（1.7 秒）" },
  "directive-limit": { reason: "decided-not-linked", note: "アルレッキーノ: 血の債務の上限を決める 35 秒の内部の窓。効果本体は directive（30 秒）" },
  // ---- E（継続ダメージ）の整理（2026-09-30 ユーザー決定）----
  "damage:Palm Vortex Max Cutting (Hold)": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Frostbound Javelin": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Wake of Earth": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Starshatter": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Spirit Blade: Cloud-Parting Star": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Icy Paw": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Starward Sword (Consecutive Slash)": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Tanglevine Shaft": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Secondary Tanglevine Shaft": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Kyougen: Five Ceremonial Plays": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Particular Field: Fetters of Phenomena": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Darkgold Wolfbite": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Secondary Explosive Shell": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Last Lightfall": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Lustrous Moonrise": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Havoc: Ruin (DoT)": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Shooting Star": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Universal Diagnosis": { reason: "decided-not-linked", note: "継続ダメージが短い単発（0.08〜2.4 秒）で、攻撃の動作時間の内側。バーにしない（ユーザー決定 2026-09-30）" },
  "damage:Rings of Searing Radiance": { reason: "covered-by-main", note: "マーヴィカのスキル: 夜魂の状態（nightsoul-blessing）で登録済み" },
  "damage:Spiritvein Damage": { reason: "covered-by-main", note: "白朮の爆発: シールド（Baizhu Seamless shield）で登録済み" },
  "damage:Blazing Threshold DMG": { reason: "covered-by-main", note: "空・蛍(炎)のスキル: ソース（traveler/common/pyro/skill.go）で、夜魂の状態が続く間 1.1 秒ごとに出る炎門のダメージと確認。夜魂の状態（nightsoul-blessing）で登録済み" },
  "damage:Dewdrop (Hold)": { reason: "decided-not-linked", note: "空・蛍(水)の長押し: ソース（traveler/common/hydro/skill.go）で、長押しの動作で放つ露雫の弾（弾道の到達まで）と確認。効果ではなくアクション自身の動作なのでバーにしない" },
  // 実測（2026-09-30）
};

/** アクション定義 ID → 理由 */
export const DEF_DECISIONS: Record<string, Decision> = {
  // ユーザー決定（2026-09-30）
  '10000112-cryo_e_hold': { reason: 'app-bar', note: 'エスコフィエの長押し: gcsim は長押しの指定（hold）を拒否して実行できず、効果も出ない。紐づけず、マスターの効果時間（20 秒）でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000114-cryo_e_hold': { reason: 'app-bar', note: 'スカークの長押し: gcsim は skirk-hold-e-anim（0 秒。動作の目印）しか出さない。紐づけず、マスターの効果時間（12.5 秒）でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000127-geo_e': { reason: 'no-bar', note: 'イルーガのスキル: gcsim v2.48.0 で実行でき、ダメージ（Dawnbearing Songbird (Tap)）のみで、バーにする状態・設置物・シールドが出ない（ソース illuga/skill.go で確認。ユーザー確認済み 2026-09-30）' },
  '10000127-geo_e_hold': { reason: 'no-bar', note: 'イルーガの長押し: 同上（Dawnbearing Songbird (Hold) のダメージのみ。ユーザー確認済み 2026-09-30）' },
  '10000104-anemo_q': { reason: 'covered-by-passive', note: 'チャスカの爆発: 出るのは固有天賦の状態（chasca-a1）だけで、スキル・爆発の効果ではない。6-3c で扱う（ユーザー決定 2026-09-30）。自動収集の chasca-plunge-available は 0.43 秒の落下攻撃の窓で誤り' },
  '10000106-pyro_e_recastframestobike': { reason: 'no-bar', note: 'マーヴィカの再発動: gcsim に新しい継続時間のイベントが出ない。バーを表示できないため登録しない' },
  '10000106-pyro_e_recastframestoring': { reason: 'no-bar', note: 'マーヴィカの再発動: 同上' },
  '10000058-electro_e': { reason: 'deferred', note: "八重神子のスキル: 6-6「ストックできるスキルへの対応」で扱う（継続ダメージの一致は取れている）" },
  // ユーザー決定（2026-09-30）: マスターの「効果時間」が、効果ではなくアクション自身の動作・別のアクションの効果のもの。gcsim の効果に紐づけない
  '10000003-anemo_e': { reason: 'no-bar', note: 'ジンのスキル: マスターの 5 秒は溜めの最大時間（動作の長さ）で、効果ではない。gcsim も状態を出さない' },
  '10000053-anemo_e_hold': { reason: 'no-bar', note: '早柚の長押し: マスターの 10 秒は長押しの最大時間（動作の長さ）で、効果ではない。gcsim も状態を出さない' },
  '10000020-electro_e_hold': { reason: 'no-bar', note: 'レザーの長押し: マスターの 18 秒（雷の印）は短押しの効果。長押しは印を作らず消費する動作で、gcsim も印の状態を出さない（短押しは razor-sigil で紐づけ済み）' },
  // ユーザー決定（2026-09-30）: 固有天賦の状態だけが出るスキル・爆発は保留（6-3c で扱う）
  '10000002-cryo_e': { reason: 'covered-by-passive', note: '神里綾華のスキル: gcsim が出すのは固有天賦の状態（ayaka-a1）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000021-pyro_e': { reason: 'covered-by-passive', note: 'アンバーのスキル: gcsim が出すのは固有天賦の状態（amber-a1）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000026-anemo_e': { reason: 'covered-by-passive', note: '魈のスキル: gcsim が出すのは固有天賦の状態（xiao-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000038-geo_q': { reason: 'covered-by-passive', note: 'アルベドの爆発: gcsim が出すのは固有天賦の状態（albedo-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000042-electro_q': { reason: 'covered-by-passive', note: '刻晴の爆発: gcsim が出すのは固有天賦の状態（keqing-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000045-cryo_e': { reason: 'covered-by-passive', note: 'ロサリアのスキル: gcsim が出すのは固有天賦の状態（rosaria-a1）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000060-hydro_e': { reason: 'covered-by-passive', note: '夜蘭のスキル: gcsim が出すのは固有天賦の状態（yelan-a1）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000069-dendro_q': { reason: 'covered-by-passive', note: 'ティナリの爆発: gcsim が出すのは固有天賦の状態（tighnari-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000084-pyro_e': { reason: 'covered-by-passive', note: 'リネのスキル: gcsim が出すのは固有天賦の状態（lyney-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000092-pyro_e': { reason: 'covered-by-passive', note: '嘉明のスキル: gcsim が出すのは固有天賦の状態（gaming-a4-heal-bonus・gaming-a4-dmg-bonus）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000097-electro_e': { reason: 'covered-by-passive', note: 'セトスのスキル: gcsim が出すのは固有天賦の状態（sethos-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000098-electro_q': { reason: 'covered-by-passive', note: 'クロリンデの爆発: gcsim が出すのは固有天賦の状態（clorinde-a4-buff）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000105-electro_e': { reason: 'covered-by-passive', note: 'オロルンのスキル: gcsim が出すのは固有天賦の状態（ororon-a1・ororon-a4）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  '10000112-cryo_q': { reason: 'covered-by-passive', note: 'エスコフィエの爆発: gcsim が出すのは固有天賦の状態（escoffier-a1・escoffier-a4-shred-cryo/hydro）だけで、スキル・爆発の効果ではない。6-3c（固有天賦の発動バフ）で扱う（ユーザー決定 2026-09-30）' },
  // ユーザー確認済み（2026-09-30）: 瞬間の効果（A）・回復のみ（B）。gcsim の実測で、バーにする状態・設置物・シールド・継続ダメージが出ない
  '10000005-anemo_e': { reason: 'no-bar', note: '空(風)のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-anemo_e_hold': { reason: 'no-bar', note: '空(風)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-cryo_q': { reason: 'no-bar', note: '空(氷)の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-dendro_e': { reason: 'no-bar', note: '空(草)のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-hydro_e': { reason: 'no-bar', note: '空(水)のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-hydro_e_shorthold0ticks': { reason: 'no-bar', note: '空(水)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-hydro_e_shorthold': { reason: 'no-bar', note: '空(水)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-hydro_e_hold': { reason: 'no-bar', note: '空(水)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000005-pyro_q': { reason: 'no-bar', note: '空(炎)の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000006-electro_e': { reason: 'no-bar', note: 'リサのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000006-electro_e_hold': { reason: 'no-bar', note: 'リサの長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-anemo_e': { reason: 'no-bar', note: '蛍(風)のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-anemo_e_hold': { reason: 'no-bar', note: '蛍(風)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-cryo_q': { reason: 'no-bar', note: '蛍(氷)の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-dendro_e': { reason: 'no-bar', note: '蛍(草)のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-hydro_e': { reason: 'no-bar', note: '蛍(水)のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-hydro_e_shorthold0ticks': { reason: 'no-bar', note: '蛍(水)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-hydro_e_shorthold': { reason: 'no-bar', note: '蛍(水)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-hydro_e_hold': { reason: 'no-bar', note: '蛍(水)の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000007-pyro_q': { reason: 'no-bar', note: '蛍(炎)の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000022-anemo_e': { reason: 'no-bar', note: 'ウェンティのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000022-anemo_e_hold': { reason: 'no-bar', note: 'ウェンティの長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000027-geo_q': { reason: 'no-bar', note: '凝光の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000032-pyro_e': { reason: 'no-bar', note: 'ベネットのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000032-pyro_e_hold': { reason: 'no-bar', note: 'ベネットの長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000036-cryo_q': { reason: 'no-bar', note: '重雲の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000043-anemo_e': { reason: 'no-bar', note: 'スクロースのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000047-anemo_e': { reason: 'no-bar', note: '楓原万葉のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000047-anemo_e_hold': { reason: 'no-bar', note: '楓原万葉の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000053-anemo_e': { reason: 'no-bar', note: '早柚のスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000053-anemo_e_shorthold': { reason: 'no-bar', note: '早柚の長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000058-electro_q': { reason: 'no-bar', note: '八重神子の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000059-anemo_q': { reason: 'no-bar', note: '鹿野院平蔵の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000062-cryo_q': { reason: 'no-bar', note: 'アーロイの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000068-electro_e': { reason: 'no-bar', note: 'ドリーのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000071-electro_e': { reason: 'no-bar', note: 'セノのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000075-anemo_q': { reason: 'no-bar', note: '放浪者の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000078-dendro_e': { reason: 'no-bar', note: 'アルハイゼンのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000078-dendro_e_hold': { reason: 'no-bar', note: 'アルハイゼンの長押し: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000078-dendro_q': { reason: 'no-bar', note: 'アルハイゼンの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000081-dendro_e': { reason: 'no-bar', note: 'カーヴェのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000086-cryo_q': { reason: 'no-bar', note: 'リオセスリの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000087-hydro_q': { reason: 'no-bar', note: 'ヌヴィレットの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000090-pyro_q': { reason: 'no-bar', note: 'シュヴルーズの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000094-geo_q': { reason: 'no-bar', note: '千織の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000102-hydro_q': { reason: 'no-bar', note: 'ムアラニの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000107-cryo_q': { reason: 'no-bar', note: 'シトラリの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000108-anemo_q': { reason: 'no-bar', note: '藍硯の爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000113-anemo_q': { reason: 'no-bar', note: 'イファの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000115-hydro_e': { reason: 'no-bar', note: 'ダリアのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000120-electro_q': { reason: 'no-bar', note: 'フリンズの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000121-hydro_e': { reason: 'no-bar', note: 'アイノのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000128-anemo_q': { reason: 'no-bar', note: 'ファルカの爆発: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000132-anemo_e': { reason: 'no-bar', note: 'プルーネのスキル: 瞬間の効果。複数回・組み合わせの実測（2026-09-30）でも、ダメージ以外のイベント（状態・設置物・シールド・回復）が出ない。ユーザー確認済み' },
  '10000014-hydro_q': { reason: 'no-bar', note: 'バーバラの爆発: 回復のイベント（Shining Miracle♪）だけで、バーにする状態・設置物・シールド・継続ダメージが無い。複数回・組み合わせの実測（2026-09-30）でも同じ。ユーザー確認済み（回復は1回ごとの瞬間の出来事）' },
  '10000015-cryo_e': { reason: 'no-bar', note: 'ガイアのスキル: 回復のイベント（Cold-Blooded Strike）だけで、バーにする状態・設置物・シールド・継続ダメージが無い。複数回・組み合わせの実測（2026-09-30）でも同じ。ユーザー確認済み（回復は1回ごとの瞬間の出来事）' },
  '10000046-pyro_q': { reason: 'no-bar', note: '胡桃の爆発: 回復のイベント（Spirit Soother）だけで、バーにする状態・設置物・シールド・継続ダメージが無い。複数回・組み合わせの実測（2026-09-30）でも同じ。ユーザー確認済み（回復は1回ごとの瞬間の出来事）' },
  '10000082-dendro_e': { reason: 'no-bar', note: '白朮のスキル: 回復のイベント（Universal Diagnosis Healing）だけで、バーにする状態・設置物・シールド・継続ダメージが無い。複数回・組み合わせの実測（2026-09-30）でも同じ。ユーザー確認済み（回復は1回ごとの瞬間の出来事）' },
  '10000083-anemo_e': { reason: 'no-bar', note: 'リネットのスキル: 回復のイベント（Enigmatic Feint）だけで、バーにする状態・設置物・シールド・継続ダメージが無い。複数回・組み合わせの実測（2026-09-30）でも同じ。ユーザー確認済み（回復は1回ごとの瞬間の出来事）' },
  '10000096-pyro_q': { reason: 'no-bar', note: 'アルレッキーノの爆発: 回復のイベント（Balemoon Rising (Heal)）だけで、バーにする状態・設置物・シールド・継続ダメージが無い。複数回・組み合わせの実測（2026-09-30）でも同じ。ユーザー確認済み（回復は1回ごとの瞬間の出来事）' },
  // ユーザー決定（2026-09-30）: gcsim が状態を返さないが、アプリのマスターの効果時間でバーを表示する（E1）
  '10000029-pyro_e': { reason: 'app-bar', note: 'クレーのスキル: ゲーム内に持続する効果があるが、gcsim は地雷はダメージのみ。紐づけず、マスターの効果時間（15 秒（ブービートラップ））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000037-cryo_e': { reason: 'app-bar', note: '甘雨のスキル: ゲーム内に持続する効果があるが、gcsim は氷蓮はダメージのみ。紐づけず、マスターの効果時間（6 秒（氷蓮））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000030-geo_q': { reason: 'app-bar', note: '鍾離の爆発: ゲーム内に持続する効果があるが、gcsim は石化の状態を出さない。紐づけず、マスターの効果時間（3.1 秒（石化））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000087-hydro_e': { reason: 'app-bar', note: 'ヌヴィレットのスキル: ゲーム内に持続する効果があるが、gcsim は状態を出さない（攻撃時の回復のみ）。紐づけず、マスターの効果時間（15 秒（源水の雫））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000094-geo_e': { reason: 'app-bar', note: '千織のスキル: ゲーム内に持続する効果があるが、gcsim は内部のタイマー（17.5 秒）でイベントを出さない。紐づけず、マスターの効果時間（17 秒（たもと））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000103-geo_q': { reason: 'app-bar', note: 'シロネンの爆発: ゲーム内に持続する効果があるが、gcsim は爆発本体の状態を出さない。紐づけず、マスターの効果時間（12 秒（歓喜リズム））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000005-hydro_q': { reason: 'app-bar', note: '空(水)の爆発: ゲーム内に持続する効果があるが、gcsim はダメージのみ。紐づけず、マスターの効果時間（4 秒（昇流統水。命ノ星座で 7 秒に延びるが、アプリの値は凸数を反映しない））でバーを表示する（ユーザー決定 2026-09-30）' },
  '10000007-hydro_q': { reason: 'app-bar', note: '蛍(水)の爆発: ゲーム内に持続する効果があるが、gcsim はダメージのみ。紐づけず、マスターの効果時間（4 秒（昇流統水。命ノ星座で 7 秒に延びるが、アプリの値は凸数を反映しない））でバーを表示する（ユーザー決定 2026-09-30）' },
  // ユーザー決定（2026-09-30）: 効果時間が長すぎるため、バーに出さない
  '10000091-geo_e': { reason: 'no-bar', note: 'ナヴィアのスキル: gcsim は個数で管理し、状態を出さない。紐づけず、バーに出さない方針（マスターの効果時間 300 秒（裂晶の欠片。ゲームの値は正しいが、ローテーション全体を覆う長さになる））（ユーザー決定 2026-09-30）' },
  '10000059-anemo_e': { reason: 'no-bar', note: '鹿野院平蔵のスキル: gcsim は内部の数で管理し、状態を出さない。紐づけず、バーに出さない方針（マスターの効果時間 60 秒（変格。ゲームの値は正しいが、ローテーション全体を覆う長さになる））（ユーザー決定 2026-09-30）' },
  // gcsim にキャラ自体が未実装のキャラ（マスターに gcsim のキーが無い）。gcsim の更新待ち
  '10000100-geo_e': { reason: 'not-in-gcsim', note: 'カチーナのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000100-geo_q': { reason: 'not-in-gcsim', note: 'カチーナの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000122-dendro_e': { reason: 'not-in-gcsim', note: 'ネフェルのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000122-dendro_q': { reason: 'not-in-gcsim', note: 'ネフェルの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000126-geo_e': { reason: 'not-in-gcsim', note: '兹白のスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000126-geo_q': { reason: 'not-in-gcsim', note: '兹白の爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000129-cryo_e': { reason: 'not-in-gcsim', note: 'ローエンのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000129-cryo_q': { reason: 'not-in-gcsim', note: 'ローエンの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000130-geo_e': { reason: 'not-in-gcsim', note: 'リンネアのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000130-geo_q': { reason: 'not-in-gcsim', note: 'リンネアの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000133-cryo_e': { reason: 'not-in-gcsim', note: 'サンドローネのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000133-cryo_q': { reason: 'not-in-gcsim', note: 'サンドローネの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000140-hydro_e': { reason: 'not-in-gcsim', note: 'ヴォジャニーツァのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000140-hydro_q': { reason: 'not-in-gcsim', note: 'ヴォジャニーツァの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000143-anemo_e': { reason: 'not-in-gcsim', note: 'ヴェスナのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000143-anemo_q': { reason: 'not-in-gcsim', note: 'ヴェスナの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000148-electro_e': { reason: 'not-in-gcsim', note: 'アリョーシャのスキル: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  '10000148-electro_q': { reason: 'not-in-gcsim', note: 'アリョーシャの爆発: gcsim（v2.47.6）にキャラ自体が未実装（マスターに gcsim のキーが無い）。gcsim が対応したら、マスターと対応表を再生成して扱いを決める（gcsim の更新待ち）' },
  // 反撃用の短いシールド（継続 1 秒未満）: バーにしない
  '10000024-electro_e': { reason: 'decided-not-linked', note: '北斗のスキル: gcsim は反撃用の短いシールド（0.38 秒）を出すが、効果として短すぎるので、紐づけず・バーも出さない' },
  '10000064-geo_e': { reason: 'decided-not-linked', note: '雲菫のスキル: gcsim は反撃用の短いシールド（0.22 秒）を出すが、効果として短すぎるので、紐づけず・バーも出さない' },
  '10000072-hydro_e': { reason: 'decided-not-linked', note: 'キャンディスのスキル: gcsim は短いシールド（0.27 秒）を出すが、効果として短すぎるので、紐づけず・バーも出さない' },
  '10000072-hydro_e_hold': { reason: 'decided-not-linked', note: 'キャンディスの長押し: gcsim は短いシールド（1.5 秒）を出すが、効果として短すぎるので、紐づけず・バーも出さない' },
};
